### ISSUE TITLE
Global Bushfires Locations Data

### ISSUE THREAD

**Issue by esharma3** [esharma3/project_australian_bushfires_webapp#3]
Find global bushfire locations data and add it to the data folder. The data must be from Jan 2015 till Feb 2020 and must have latitudes and longitudes for the fire locations.

**Comment by Aspace-dev** [comment]
Resolved issue and submitted pull request for updated load_to_mysql.py file and .gitignore.
Data should be loading in the correct format and optimal size.
New csv file added to .gitignore
