### ISSUE TITLE
Kangaroo Island/National Parks Data

### ISSUE THREAD

**Issue by esharma3** [esharma3/project_australian_bushfires_webapp#6]
Find all bushfire data (fires, animals, firefighters, anything that would make sense to add to our KI template)  related to Kangaroo Island or other National Parks. The data could be in the form of csv files or can be scraped.

**Comment by JDurnan78** [comment]
Are we still going to try to single out a certain area or can we close/rename this one.  I've been scraping additional impact data that includes these areas but is not exclusively Kangaroo Island or National Parks.
