### ISSUE TITLE
Bushfire Impacts Data

### ISSUE THREAD

**Issue by esharma3** [esharma3/project_australian_bushfires_webapp#7]
Find all the data that can be represented as 'IMPACTS of BUSHFIRE' in Australia. The impacts could be on human, wildlife, economic, psychological etc. The data could be in the form of csv, API or can be scraped.

**Comment by jdaltuvec** [comment]
Wildlife impact of fire in here: 
[protected-species-in-fire-affected-areas-20Jan.xlsx](https://github.com/esharma3/project_australian_bushfires_webapp/files/4302254/protected-species-in-fire-affected-areas-20Jan.xlsx)
